### ISSUE TITLE
Line counting is wrong

### ISSUE THREAD

**Issue by CharlesNepote** [utsukushii/LT-Perl#1]
For example:
`Compile error: Global symbol "$param" requires explicit package name at (eval 350) line 8.BEGIN not safe after errors--compilation aborted at (eval 350) line 8.`
is given for a problem line **73** and not 8 (see screenshot below).

![capture du 2015-02-06 13 23 57](https://cloud.githubusercontent.com/assets/562352/6079278/8e2f6284-ae03-11e4-81f5-33ce0691dfe6.png)

All scripts tested have shown such a problem.

**Comment by utsukushii** [comment]
This should be fixed in version 0.0.8. To update in LightTable:
- refresh the plugin list
- update the Perl plugin
- restart LightTable
